<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ApplicationRental extends Model
{
    use HasFactory;



    protected $fillable = [
        'passport',
        'job_letter',
        'id_card',
        'payslips',
        'applicant_surname',
        'applicant_first',
        'applicant_middle',
        'applicant_address',
        'co_applicant_surname',
        'co_applicant_name',
        'co_applicant_middle',
        'co_applicant_address',
        'maiden_name',
        'date_of_birth',
        'tamis_number',
        'phone_home',
        'phone_work',
        'phone_cell',
        'email_field',
        'marital_status',
        'citizenship_field',
        'country_of_residence',
        'employer_field',
        'pay_period',
        'employment_status',
        'co_maiden_name',
        'co_national_registration_number',
        'co_tamis_number',
        'co_date_of_birth',
        'co_phone_home',
        'co_phone_work',
        'co_phone_cell',
        'co_email',
        'co_marital_status',
        'co_citizenship_field',
        'co_country_of_residence',
        'co_employer_field',
        'co_occupation_field',
        'co_period_of_employment',
        'co_salary',
        'co_pay_period',
        'co_employment_status',
        'national_registration_number',
        'employer',
        'occupation',
        'citizenship',
        'income',
        'telephone',
        'size_of_family',
        'adults',
        'children',
        'own_landorproperty',
        'state_address',
        'financial_institution',
        'give_details',
        'occupedaunit',
        'occuppiedUnit',
        'photograph',
        'addmore',
        'tenantorlodger',
        'addressoflandlord',
        'present_accommodation',
        'structureofhouse',
        'rental_date',
        'typeofsanityfacilities',
        'water_supply',
        'housingofficercomments',
        'acknowledged',
        'dayof',
        'year',
        'by',
        'keysreceived',
        'thiskeys',
        'dayofkeys',
        'yearkeys',
        'whitnessed',
        'thiswhitnessed',
        'dayofwhitnessed',
        'yearwhitnessed',
        'housingofficer',
        'signatures',
        'datedthis',
        'dayofdatedthis',
        'yeardatedthis',
        'applicant_address2',
'co_applicant_address2',
'applicant_parish',
'co_applicant_parish',
'co_email_field',
'co_client_id',
'client_id'

    ];
}
