<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ApplicationForThePurchase extends Model
{
    use HasFactory;

    protected $fillable = [
        'salutation',
        'applicant_surname',
        'applicant_first',
        'applicant_middle',
        'applicant_maiden_name',
        'applicant_national_registration_number',
        'applicant_tamis_no',
        'applicant_address',
        'applicant_date_birth',
        'applicant_phone_home',
        'applicant_phone_work',
        'applicant_phone_cell',
        'applicant_email',
        'app_employer_field',
        'app_occupation_field',
        'app_period_of_employment',
        'app_salary',
        'app_employment_status',
        'marital_status',
        'applicant_citizenship',
        'applicant_country_of_residence',
        'coapplicant_salutation',
        'coapplicant_surname',
        'coapplicant_first',
        'coapplicant_middle',
        'coapplicant_maiden_name',
        'coapplicant_national_registration_number',
        'coapplicant_tamis_no',
        'coapplicant_address',
        'coapplicant_date_birth',
        'coapplicant_phone_home',
        'coapplicant_phone_work',
        'coapplicant_phone_cell',
        'coapplicant_email',
        'co_marital_status',
        'co_applicant_citizenship',
        'co_applicant_country_of_residence',
        'co_app_employer_field',
        'co_app_occupation_field',
        'co_app_period_of_employment',
        'co_app_salary',
        'co_app_pay_period',
        'co_app_employment_status',
        'applicant_period',
        'co_applicant_period',
        'applicant_occup',
        'co_applicant_occup',
        'applicant_employer',
        'co_applicant_employer',
        'applicant_salary',
        'co_applicant_salary',
        'government',
        'private',
        'self',
        'monthly',
        'weekly',
        'forth_nightly',
        'house_type',
        'purchasing_options',
        'preferedhousetype',
        'no_of_occupants',
        'children_ages',
        'disabilitieswithinthehousehold',
        'alternative',
        'alternative_amount',
        'alternative1',
        'alternative_amount2',
        'areyourenting',
        'ifyeshowmuch',
        'yourownland',
        'tenant',
        'land_or_agent',
        'financethepurchsaseproporty',
        'mortgage_or_loan',
        'the_amount_of_deposit',
        'land_or_property',
        'qualifyngamount',
        'signature_applican',
        'signature_coapplicant',
        'dateend',
        'recommended_by',
        'approved',
        'date_official',
        'remarks_official',
        'qualifying_amount_official',
        'applicant_address2',
        'applicant_address3',
        'applicant_parish',
        'coapplicant_address2',
        'coapplicant_address3',
        'coapplicant_parish',
        'addmore',
        'land_or_lot',
        'bankstatements'
    ];
}
